# Generated by Django 3.1.3 on 2020-12-01 00:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='Contact')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Immobilier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('pays', models.CharField(max_length=50)),
                ('types', models.CharField(max_length=50, verbose_name='Type')),
                ('price', models.IntegerField(verbose_name='Prix')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
                ('area', models.IntegerField(verbose_name='Superficie')),
                ('desc', models.TextField(verbose_name='Description votre bien')),
                ('picture_one', models.ImageField(upload_to=None, verbose_name='image')),
                ('picture_two', models.ImageField(null=True, upload_to=None, verbose_name='image 1')),
                ('picture_three', models.ImageField(null=True, upload_to=None, verbose_name='image 2')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Appart',
            fields=[
                ('immobilier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='immobapp.immobilier')),
                ('num_piece', models.IntegerField(verbose_name='Nombre de pièce')),
                ('num_toilete', models.IntegerField(verbose_name='Nombre de toillete')),
            ],
            bases=('immobapp.immobilier',),
        ),
    ]
