# Generated by Django 3.1.3 on 2020-12-01 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immobapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilier',
            name='pays',
        ),
        migrations.AddField(
            model_name='immobilier',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='Pays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immobilier',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='picture_three',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='picture_two',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='image 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, verbose_name='Prénom'),
            preserve_default=False,
        ),
    ]
