# Generated by Django 3.1.3 on 2020-12-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobapp', '0002_auto_20201201_1452'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
