# Generated by Django 3.1.3 on 2020-12-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('immobapp', '0003_auto_20201201_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nom ville')),
            ],
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='country',
            field=models.CharField(max_length=128, verbose_name='Pays'),
        ),
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_type', models.CharField(max_length=50, verbose_name='Type de besoin')),
                ('city', models.CharField(max_length=50, verbose_name='Ville')),
                ('country', models.CharField(max_length=50, verbose_name='Pays')),
                ('min_price', models.IntegerField(verbose_name='Prix min')),
                ('max_price', models.IntegerField(verbose_name='Prix max')),
                ('area', models.IntegerField(verbose_name='Superficie')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publicatication')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publié par')),
            ],
        ),
        migrations.AlterField(
            model_name='immobilier',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='immobapp.ville', verbose_name='Ville'),
        ),
    ]
