# Generated by Django 3.1.3 on 2020-12-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immobapp', '0005_auto_20201203_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='immobilier',
            name='owner',
        ),
    ]
